[theme]
base = "dark"
primaryColor = "#1DB954"  # Verde vibrante (tipo Spotify)
backgroundColor = "#0E1117"  # Preto grafite
secondaryBackgroundColor = "#1E222A"  # Cinza escuro para painéis e cards
textColor = "#FFFFFF"  # Texto branco puro
font = "sans serif"

[server]
enableCORS = false
headless = true
